DROP TABLE IF EXISTS track_information;

DROP TABLE IF EXISTS artists;

DROP TABLE IF EXISTS tracks;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS artist;

DROP TYPE IF EXISTS track;

DROP TYPE IF EXISTS time_span;